### ISSUE TITLE
add LogType SVG icons

### ISSUE THREAD

**Issue by Longri** [Longri/cachebox3.0#108]
- [x] found, // 0 
![log0icon](https://cloud.githubusercontent.com/assets/2542295/26670193/0e81c308-46b1-11e7-88fe-999c7cb09402.png)
   - [x] didnt_find, // 1
![log1icon](https://cloud.githubusercontent.com/assets/2542295/26670234/31c88dc4-46b1-11e7-8da3-127db9aa34c3.png)

   - [x] note, // 2
![log2icon](https://cloud.githubusercontent.com/assets/2542295/26670271/5355b674-46b1-11e7-9c59-73a145624183.png)

   - [x] published, // 3
![log3icon](https://cloud.githubusercontent.com/assets/2542295/26670281/5d018fc2-46b1-11e7-8cd4-1bfadedd2a69.png)

   - [x] enabled, // 4
![log4icon](https://cloud.githubusercontent.com/assets/2542295/26670290/644c6360-46b1-11e7-8368-2eb6e781244d.png)

   - [x] needs_maintenance, // 5
![log5icon](https://cloud.githubusercontent.com/assets/2542295/26670305/71cf255e-46b1-11e7-8d0b-24f4552f55d6.png)

   - [x] temporarily_disabled, // 6
![log6icon](https://cloud.githubusercontent.com/assets/2542295/26670310/765a4928-46b1-11e7-830a-e151fa6e2ab7.png)

   - [x] owner_maintenance, // 7
![log7icon](https://cloud.githubusercontent.com/assets/2542295/26670317/7d2ef104-46b1-11e7-8a5e-9af7994d20be.png)

   - [x] will_attend, // 8
![log8icon](https://cloud.githubusercontent.com/assets/2542295/26670331/8cc35326-46b1-11e7-869c-9950b98fd3d5.png)

   - [x] attended, // 9
![log9icon](https://cloud.githubusercontent.com/assets/2542295/26670338/90f8caca-46b1-11e7-8cfb-f51840e62304.png)

   - [x] webcam_photo_taken, // 10
![log10icon](https://cloud.githubusercontent.com/assets/2542295/26670347/96825010-46b1-11e7-844b-aac2b311e72f.png)

   - [x] archived, // 11
![log11icon](https://cloud.githubusercontent.com/assets/2542295/26670348/9c91be50-46b1-11e7-91e7-e18d62a68611.png)

   - [x] reviewer_note, // 12
![log12icon](https://cloud.githubusercontent.com/assets/2542295/26670352/a18a878e-46b1-11e7-8c50-6f1b962a52d0.jpg)

   - [x] needs_archived, // 13
![log13icon](https://cloud.githubusercontent.com/assets/2542295/26670359/a6b33828-46b1-11e7-9b77-13127374f710.png)

   - [ ] unarchive, // 14
![log14icon](https://cloud.githubusercontent.com/assets/2542295/26670377/b65aa432-46b1-11e7-9af6-3c4399f5738b.png)

   - [ ] retract, // 15
![log15icon](https://cloud.githubusercontent.com/assets/2542295/26670382/bdbe15d8-46b1-11e7-99fe-b4d4a5a187d2.png)

   - [x] update_coord, // 16
![log16icon](https://cloud.githubusercontent.com/assets/2542295/26670401/c689ba28-46b1-11e7-9f5e-cab7762cd5d9.png)

   - [x] retrieve, // 17
![tbpicked](https://cloud.githubusercontent.com/assets/2542295/26670434/f4fddcae-46b1-11e7-87b3-c773422cec83.png)

   - [x] dropped_off, // 18
![tbdrop](https://cloud.githubusercontent.com/assets/2542295/26670440/fb5d0f16-46b1-11e7-9eb0-89706e784dea.png)

   - [x] mark_missing, // 19
   - [x] grab_it, // 20
![tbgrab](https://cloud.githubusercontent.com/assets/2542295/26670542/51212a40-46b2-11e7-8f41-e42bb8f943f2.png)

   - [x] discovered, // 21
![tbdiscover](https://cloud.githubusercontent.com/assets/2542295/26670551/5836ff8a-46b2-11e7-8610-f8518f61b7ae.png)

   - [x] move_to_collection, // 22
   - [x] move_to_inventory, // 23
   - [x] announcement, // 24
   - [x] visited, // 25

**Comment by arbor95** [comment]
done
