### ISSUE TITLE
Add AutoResort

### ISSUE THREAD

**Issue by Longri** [Longri/cachebox3.0#116]

**Comment by arbor95** [comment]
done
bleibt jetzt so lange an, bis es wieder ausgeschaltet wird (entweder über den quickbutton oder das cachelistContextmenü). Beim CB2 wurde es ja auch durch die manuelle Auswahl eines anderen Caches ausgeschaltet. Das habe ich nicht implementiert. Sortiert wird nach dem Abstand vom EventHandler.getMyPosition() (GPS).

Jedesmal beim Anklicken der Cacheliste wird nach dem Abstand zum gerade selektierten Cache sortiert. (Ich glaube in CB2 wird dabei nicht neu sortiert, oder?). Beim Klick auf "Liste neu sortieren" wird nach dem Abstand vom gerade selektierten Cache sortiert (falls autoresort nicht aktiv ist).
