### ISSUE TITLE
Store generated API-Key failed 

### ISSUE THREAD

**Issue by Longri** [Longri/cachebox3.0#205]

**Comment by arbor95** [comment]
First part of bug: Even if a key is generated succesful over the webview, the webview is called a second time.
Second: If called from settings/login the values of username and API-key are not shown. But they are visible if youclick on the the setting item.
If you leave the settings by save, the values are not written to the database (perhaps simply the dirty flags is not set, by changing values).
On next start of CB the value of API Key (?username) is missing.

**Comment by arbor95** [comment]
finally corrected with 3209
