### ISSUE TITLE
Select MapState.Wp with change of current waypoint/cache

### ISSUE THREAD

**Issue by Longri** [Longri/cachebox3.0#213]

**Comment by arbor95** [comment]
CB2 doesn't have this feature.
It is not really necessary or helpful.

There has been an arrow on the map for directly positioning the map to the selected cache or way-point. That would be more useful.

**Comment by arbor95** [comment]
Done for waypointView

**Comment by arbor95** [comment]
done for all coordinate changed events (mapview is not one of this)
